name: presentation
description: The presentation layer for the expense tracker app.
version: 0.0.1+4
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  domain:
    path: ../domain
  data:
    path: ../data

  hive_flutter: ^1.1.0
  supabase_flutter: ^2.9.1
  path_provider: ^2.1.5
  lottie: ^3.3.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  supabase: ^2.8.0
  get_it: ^8.0.3
  uuid: ^4.5.1
  flutter_floating_bottom_bar: ^1.3.0


  fpdart: ^1.1.1
  font_awesome_flutter: ^10.8.0

  fl_chart: ^1.0.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15

  bloc_test: ^10.0.0
  mockito: ^5.4.6


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/animations/