name: domain
description: The core domain logic for the expense tracker app.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.7
  fpdart: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0