# .github/workflows/android_release.yml

name: Android Release APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest


    permissions:
      contents: write
    # -----------------------------------------

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0' 
          channel: 'stable'

      # Step 3: Get the app version
      - name: Get pubspec version
        id: pubspec
        uses: CumulusDS/get-yaml-paths-action@v1
        with:
          file: presentation/pubspec.yaml
          version: version


      # Step 5: Install dependencies and build the APK
      - name: Install Dependencies and Build APK
        working-directory: ./presentation
        run: |
          flutter pub get
          flutter build apk --release --obfuscate --split-debug-info=./debug_info

      # Step 6: Create a GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.pubspec.outputs.version }}
          name: Release v${{ steps.pubspec.outputs.version }}
          generate_release_notes: true
          files: presentation/build/app/outputs/flutter-apk/app-release.apk
